
---
server:
  port: 8080
spring:
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      properties:
        spring.json.trusted.packages: "*"
  redis:
    host: localhost
    port: 6379
---
